import { useEffect, useMemo, useState } from 'react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell } from 'recharts';
import AdminLayout from '../../components/admin/AdminLayout';
import { useAuth } from '../../context/AuthContext';

const API = import.meta.env.VITE_API_URL || 'http://localhost:5008/api';
const COLORS = ['#22c55e', '#f59e0b', '#8b5cf6', '#3b82f6', '#ec4899'];
export default function AdminAnalytics() {
  const { token } = useAuth();
  const [data, setData] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { fetch(`${API}/admin/summary`, { headers: { Authorization: `Bearer ${token}` } }).then(async response => { const body = await response.json(); if (!response.ok) throw new Error(body.message); return body; }).then(setData).catch(err => setError(err.message)); }, [token]);
  const categories = useMemo(() => (data?.categoryData || []).map((item, index) => ({ ...item, color: COLORS[index % COLORS.length] })), [data]);
  const revenue = Number(data?.counts?.revenue || 0);
  return <AdminLayout><div className="mb-8"><h1 className="text-2xl font-bold text-forest-900 mb-2">Analytics</h1><p className="text-forest-600">Live figures calculated from database orders and products</p></div>{error && <p className="mb-4 text-red-700">{error}</p>}<div className="grid sm:grid-cols-3 gap-6 mb-8">{[['Revenue', `रू ${revenue.toLocaleString()}`], ['Customers', data?.counts?.customers || 0], ['Orders', data?.counts?.orders || 0]].map(([label, value]) => <div key={label} className="glass-card rounded-2xl p-6"><p className="text-sm text-forest-600">{label}</p><p className="text-2xl font-bold">{data ? value : '—'}</p></div>)}</div><div className="grid lg:grid-cols-2 gap-6 mb-8"><section className="glass-card rounded-2xl p-6"><h2 className="font-bold mb-6">Monthly revenue</h2><ResponsiveContainer width="100%" height={260}><LineChart data={data?.monthlyData || []}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Line type="monotone" dataKey="revenue" stroke="#22c55e" strokeWidth={2.5} /></LineChart></ResponsiveContainer></section><section className="glass-card rounded-2xl p-6"><h2 className="font-bold mb-6">Orders per month</h2><ResponsiveContainer width="100%" height={260}><BarChart data={data?.monthlyData || []}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><Bar dataKey="orders" fill="#16a34a" /></BarChart></ResponsiveContainer></section><section className="glass-card rounded-2xl p-6"><h2 className="font-bold mb-6">Top products</h2>{data?.topProducts?.map(product => <div key={product.id} className="flex justify-between py-3 border-b"><span>{product.name}</span><strong>{product.sales} sold</strong></div>) || <p className="text-forest-500">No sales data yet.</p>}</section><section className="glass-card rounded-2xl p-6"><h2 className="font-bold mb-6">Product categories</h2><ResponsiveContainer width="100%" height={200}><PieChart><Pie data={categories} dataKey="value" nameKey="name" outerRadius={75}>{categories.map(category => <Cell key={category.name} fill={category.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></section></div></AdminLayout>;
}
